Repository Tmpecho/idatt2003-mappe-2025-gr57, pull requests merged in 2025-04, with the labels that each got.

#49 Refactor/move UI out from models
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/domain/board/GameBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/domain/board/Tile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/domain/board/TileObserver.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/view/MainView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/domain/board/Connector.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/domain/board/Ladder.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/domain/board/Snake.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/domain/board/SnakesAndLaddersBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/domain/board/SnakesAndLaddersTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/view/SnakesAndLaddersBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/view/SnakesAndLaddersTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/view/SnakesAndLaddersView.java
Labels: refactor

#50 Add JSON-serializers to SnakesAndLadders
  .gitignore
  pom.xml
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/controller/GameController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/domain/board/GameBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/common/view/MainView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/controller/SnakesAndLaddersController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesAndLadders/domain/board/SnakesAndLaddersBoard.java
Labels: enhancement

#54 Rename classes including SnakesAndLadders to SnL
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnLBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnLTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/controller/SnLController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/persistence/mapper/SnLMapper.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
Labels: refactor

#55 Refactor the loadMenu method in MainView for improved clarity
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
Labels: refactor

#59 refactor: move color mapping to util from domain
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/domain/player/PlayerColor.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/util/PlayerColorMapper.java
Labels: refactor

#63 fix: use return value of dir.mkdirs() and add error handling to it
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
Labels: bug

#66 fix: make GameObserver and related classes generic to support different position types
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/engine/controller/GameController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/engine/event/GameObserver.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/engine/event/TileObserver.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnLBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
Labels: refactor
