Repository Tmpecho/idatt2003-mappe-2025-gr57, pull requests merged in 2025-05, with the labels that each got.

#72 Remove logging notifications from Dice class for error handling
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/domain/dice/Dice.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/util/LoggingNotification.java
Labels: bug

#64 feat: create cluedo game board with view
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/domain/board/GameBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/domain/player/PlayerColor.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/engine/event/TileObserver.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/AbstractCluedoTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/BorderTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CorridorTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/RoomTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnLBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/controller/SnLController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/view/SnLTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/util/PlayerColorMapper.java
Labels: enhancement

#82 misc: add formatting step and include 'main' branch in workflows
  .github/workflows/maven.yml
Labels: chore

#84 Add player movement
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/RoomTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoTileView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/util/PlayerTokenFactory.java
Labels: enhancement

#86 feat(cluedo): add cards
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Card.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/CardType.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Cards.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/player/CluedoPlayer.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
Labels: enhancement

#89 feat(cluedo): refactor suspects
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Cards.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Suspect.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/SuspectTest.java
Labels: refactor

#91 refactor: remove generic `incrementPlayerPosition` method
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/domain/board/GameBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnLBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/action/RollAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/controller/SnLController.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoardTest.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnLBoardTest.java
Labels: refactor

#95 refactor(cluedo): refactor cluedo logic
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/AccusationAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/MoveAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/RollAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/SuggestionAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoardTest.java
Labels: refactor

#98 feat(cluedo): create the accusation system
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Card.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/CardType.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Cards.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Room.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Suspect.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Weapon.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/player/CluedoPlayer.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/AccusationAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/SuggestionAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/SuspectTest.java
Labels: enhancement

#100 feat(cluedo): implement the intel functionality
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Card.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Room.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Suspect.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Weapon.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/SuggestionAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
Labels: enhancement

#101 feat(cluedo): Add note-taking functionality for Cluedo players
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/player/CluedoPlayer.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
Labels: enhancement

#106 refactor: misc refactoring
  src/main/java/edu/ntnu/idi/idatt/boardgame/core/domain/board/Tile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/card/Room.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/action/RollAction.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoBoardView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/view/CluedoView.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnlBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/domain/board/SnlTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/controller/SnlController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/persistence/mapper/SnlMapper.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/util/LoggingNotification.java
Labels: refactor

#107 feat(cluedo): implement Cluedo game state saving and loading
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/RoomTile.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/Phase.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoController.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/persistence/JsonCluedoGameStateRepository.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/persistence/dto/CluedoGameStateDto.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/persistence/mapper/CluedoMapper.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/persistence/mapper/SnlMapper.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/MainView.java
Labels: enhancement

#112 chore: remove player name field for cluedo
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/domain/board/CluedoBoard.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/dto/PlayerSetupDetails.java
  src/main/java/edu/ntnu/idi/idatt/boardgame/ui/view/PlayerConfigurationView.java
Labels: enhancement

#116 feat: write tests for controllers
  src/main/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/controller/SnlController.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/cluedo/engine/controller/CluedoControllerTest.java
  src/test/java/edu/ntnu/idi/idatt/boardgame/games/snakesandladders/engine/controller/SnlControllerTest.java
Labels: enhancement
